//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsmntYear
    {
        public int AsmntYearId { get; set; }
        public int SchoolId { get; set; }
        public string AsmntYearCode { get; set; }
        public string AsmntYearDesc { get; set; }
        public System.DateTime AsmntYearStartDt { get; set; }
        public Nullable<System.DateTime> AsmntYearEndDt { get; set; }
        public string CurrentInd { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
