//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehavioursPA
    {
        public int BehavioursPAId { get; set; }
        public int StudentPersonalId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> BehaviorId { get; set; }
        public string BehaviourName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Score { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
