//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Behavior
    {
        public string StudentName { get; set; }
        public string StudentGender { get; set; }
        public string SchoolName { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Behaviour { get; set; }
        public string PartialInterval { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Duration { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<int> NumOfTimes { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UserName { get; set; }
        public string TeacherGender { get; set; }
    }
}
