//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviourCalc
    {
        public int BehaviourCalcId { get; set; }
        public int MeasurmentId { get; set; }
        public int StudentId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<bool> IOAFlag { get; set; }
        public Nullable<int> IOAUser { get; set; }
        public System.DateTime Date { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<bool> IsPartial { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> Yes_No { get; set; }
    }
}
