//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiweeklyStatu
    {
        public int StatusId { get; set; }
        public Nullable<bool> ChooseAssessment { get; set; }
        public Nullable<bool> ScoreAssessment { get; set; }
        public Nullable<bool> GenerateIEP { get; set; }
        public Nullable<bool> CompleteIEP { get; set; }
        public Nullable<bool> SubmitForApprove { get; set; }
        public Nullable<bool> NewLessonPlan { get; set; }
        public Nullable<bool> CustomLessonPlan { get; set; }
        public Nullable<bool> AllLessonsApprove { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
