//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ClassId { get; set; }
        public int SchoolId { get; set; }
        public string ClassCd { get; set; }
        public string ClassName { get; set; }
        public string ClassDesc { get; set; }
        public Nullable<int> ResidenceInd { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<int> MaxStudents { get; set; }
    }
}
