//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class clvAsmtTool
    {
        public int clvAsmtToolId { get; set; }
        public int StdtCoverSheetId { get; set; }
        public string TrgetBehav { get; set; }
        public string Functions { get; set; }
        public string AnalysisTool { get; set; }
    }
}
