//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class clvRecChange
    {
        public int clvRecChangeId { get; set; }
        public int StdtCoverSheetId { get; set; }
        public string Recomendation { get; set; }
        public string TimeLine { get; set; }
        public string PersonResponsible { get; set; }
    }
}
