//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPersonal
    {
        public int ContactPersonalId { get; set; }
        public int StudentPersonalId { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Relation { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> SocSecurityNo { get; set; }
        public string Employer { get; set; }
        public string Occupation { get; set; }
        public string Suffix { get; set; }
        public string Role { get; set; }
        public string Spouse { get; set; }
        public string PrimaryLanguage { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<bool> HispanicLatino { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> BirthDateVerification { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string PlaceOfBirth { get; set; }
        public string CountyOfBirth { get; set; }
        public Nullable<int> StateOfBirth { get; set; }
        public Nullable<int> CountryOfBirth { get; set; }
        public string CountryOfCitizenship { get; set; }
        public string CountryOfResidency { get; set; }
        public Nullable<System.DateTime> CountryArrivalDate { get; set; }
        public Nullable<int> CitizenshipStatus { get; set; }
        public Nullable<int> EnglishProficiency { get; set; }
        public string LanguageList { get; set; }
        public string DwellingArrangementCode { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> EmployerType { get; set; }
        public string ContactFlag { get; set; }
        public Nullable<int> Status { get; set; }
        public string Education { get; set; }
        public Nullable<int> EducationLevel { get; set; }
        public string GrossIncome { get; set; }
        public string CauseDeath { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsEmergency { get; set; }
        public Nullable<bool> IsIncident { get; set; }
        public Nullable<bool> IsBilling { get; set; }
        public Nullable<bool> IsSchool { get; set; }
        public Nullable<int> SpouseId { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsCorrespondence { get; set; }
        public Nullable<bool> IsCustody { get; set; }
        public Nullable<bool> IsGuardian { get; set; }
        public Nullable<bool> IsNextOfKin { get; set; }
        public Nullable<bool> ApprovedVisitor { get; set; }
        public Nullable<bool> IsOffCampus { get; set; }
        public Nullable<bool> IsOnCampusAlone { get; set; }
        public Nullable<bool> IsOnCampusWithStaff { get; set; }
    }
}
