//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrntRecomendation
    {
        public int CrntId { get; set; }
        public Nullable<int> StdtCvrId { get; set; }
        public string Notes { get; set; }
        public string Recomendations { get; set; }
        public string PersonResp { get; set; }
        public Nullable<System.DateTime> CompletionDateGoal { get; set; }
        public string CrntRecoType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
