//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaganosesPA
    {
        public int DiaganosePAId { get; set; }
        public int StudentPersonalId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string Diaganoses { get; set; }
        public string BloodGroup { get; set; }
        public string AllergiesAndReactions { get; set; }
        public string SummaryHealthProblem { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
