//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTempHdr
    {
        public int DSTempHdrId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> LessonPlanId { get; set; }
        public Nullable<int> TeachingProcId { get; set; }
        public Nullable<bool> ModificationInd { get; set; }
        public string DSTemplateName { get; set; }
        public string DSTemplateDesc { get; set; }
        public Nullable<int> VerNbr { get; set; }
        public Nullable<System.DateTime> VerBeginDate { get; set; }
        public Nullable<System.DateTime> VerEndDate { get; set; }
        public string CurrVerInd { get; set; }
        public string MultiSetsInd { get; set; }
        public string MultiStepInd { get; set; }
        public string SkillType { get; set; }
        public Nullable<int> NbrOfTrials { get; set; }
        public string ChainType { get; set; }
        public Nullable<int> PromptTypeId { get; set; }
        public Nullable<int> TotNbrOfSessions { get; set; }
        public Nullable<int> SessionFreq { get; set; }
        public Nullable<int> NbrOfSession { get; set; }
        public string CompCurrInd { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string IsVisualTool { get; set; }
        public Nullable<int> VTLessonId { get; set; }
        public string BaselineProc { get; set; }
        public Nullable<System.DateTime> BaselineStart { get; set; }
        public Nullable<System.DateTime> BaselineEnd { get; set; }
        public string CorrRespDef { get; set; }
        public string CorrectResponse { get; set; }
        public string StudCorrRespDef { get; set; }
        public string IncorrRespDef { get; set; }
        public string StudIncorrRespDef { get; set; }
        public string CorrectionProc { get; set; }
        public string ReinforcementProc { get; set; }
        public string TeacherRespReadness { get; set; }
        public string StudentReadCrita { get; set; }
        public string MajorSetting { get; set; }
        public string MinorSetting { get; set; }
        public string LessonDefInst { get; set; }
        public string Mistrial { get; set; }
        public string MistrialResponse { get; set; }
        public string TeacherPrepare { get; set; }
        public string StudentPrepare { get; set; }
        public string StudResponse { get; set; }
        public string DSMode { get; set; }
        public string RejectedReason { get; set; }
        public string PrevStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> StdtLessonplanId { get; set; }
        public Nullable<bool> isDynamic { get; set; }
        public string Baseline { get; set; }
        public string Objective { get; set; }
        public Nullable<int> TotalTaskType { get; set; }
        public Nullable<int> TaskOther { get; set; }
        public string GeneralProcedure { get; set; }
        public string MatchToSampleType { get; set; }
        public string Materials { get; set; }
        public string PreReq { get; set; }
        public string SpecEntryPoint { get; set; }
        public string SpecStandard { get; set; }
        public string ApprNoteLessonProc { get; set; }
        public string ApprNoteMeasurement { get; set; }
        public string ApprNotePrompt { get; set; }
        public string ApprNoteSet { get; set; }
        public string ApprNoteStep { get; set; }
        public string ApprNoteTypeInstruction { get; set; }
        public string FrameandStrand { get; set; }
        public string TotalTaskFormat { get; set; }
        public string ApprNoteLessonInfo { get; set; }
        public string LessonPlanGoal { get; set; }
        public string MatchToSampleRecOrExp { get; set; }
        public int IsMT_IOA { get; set; }
        public string Reason_New { get; set; }
        public int NoofTimesTried { get; set; }
        public Nullable<int> LessonOrder { get; set; }
        public string deletessn { get; set; }
        public Nullable<int> crntset { get; set; }
        public Nullable<int> crntstep { get; set; }
        public Nullable<int> crntprompt { get; set; }
        public Nullable<int> nextsetno { get; set; }
    }
}
