//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTempStep
    {
        public int DSTempStepId { get; set; }
        public int SchoolId { get; set; }
        public int DSTempHdrId { get; set; }
        public Nullable<int> DSTempSetId { get; set; }
        public Nullable<int> PrevStepId { get; set; }
        public string StepCd { get; set; }
        public string StepName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string PreDefinedInd { get; set; }
        public Nullable<int> DSTempParentStepId { get; set; }
        public Nullable<int> CustomById { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<int> VTStepId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDynamic { get; set; }
    }
}
