//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTempSet
    {
        public int DSTempSetId { get; set; }
        public int SchoolId { get; set; }
        public int DSTempHdrId { get; set; }
        public Nullable<int> PrevSetId { get; set; }
        public string SetCd { get; set; }
        public string SetName { get; set; }
        public string Samples { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<int> VTSetId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
