//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTempSetStatu
    {
        public int DSTempSetStatusId { get; set; }
        public Nullable<int> DSTempHdrId { get; set; }
        public Nullable<int> CurrentSetId { get; set; }
        public Nullable<int> CurrentStepId { get; set; }
        public Nullable<int> CurrentPromptId { get; set; }
        public Nullable<bool> IsMaintanance { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
