//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public int StudentPersonalId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<int> EventType { get; set; }
        public string EventsName { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
        public Nullable<int> EventStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Contact { get; set; }
        public string Note { get; set; }
        public string Username { get; set; }
        public Nullable<bool> IsSystemEvent { get; set; }
    }
}
