//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int EventLogId { get; set; }
        public Nullable<int> StudentPersonalId { get; set; }
        public Nullable<int> ObjectTypeId { get; set; }
        public string ObjectType { get; set; }
        public string ObjectField { get; set; }
        public string ObjectFieldType { get; set; }
        public string PreviousValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
