//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP
    {
        public string StudentName { get; set; }
        public string StudentGender { get; set; }
        public string SchoolName { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> Age { get; set; }
        public string LessonPlanName { get; set; }
        public string GoalName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string IEPStatus { get; set; }
    }
}
