//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_PE12_DateOfRev
    {
        public int Id { get; set; }
        public Nullable<int> StdtIEP_PEId { get; set; }
        public string DateofRevision { get; set; }
        public string Participants { get; set; }
        public string IEPSection { get; set; }
    }
}
