//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_PE2_Team
    {
        public int Id { get; set; }
        public Nullable<int> StdtIEP_PEId { get; set; }
        public string ParentName { get; set; }
        public string ParentSing { get; set; }
        public string StudentName { get; set; }
        public string StudentSign { get; set; }
        public string RegEduTeacherName { get; set; }
        public string regEduTeacherSign { get; set; }
        public string SpclEduTeacherName { get; set; }
        public string SpclEduTeacherSign { get; set; }
        public string LocalEdAgencyName { get; set; }
        public string localEdAgencySign { get; set; }
        public string CareerEdRepName { get; set; }
        public string careerEdRepSign { get; set; }
        public string CommunityAgencyName { get; set; }
        public string CommunityAgencySign { get; set; }
        public string TeacherGiftedName { get; set; }
        public string TeacherGiftedSign { get; set; }
        public string WittenInput { get; set; }
    }
}
