//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEP_PE_Details
    {
        public int Id { get; set; }
        public Nullable<int> StdtIEP_PEId { get; set; }
        public string IEP1DocumentedBy { get; set; }
        public string IEP3ParentSign { get; set; }
        public Nullable<bool> IEP4IsBlind { get; set; }
        public Nullable<bool> IEP4Isdeaf { get; set; }
        public Nullable<bool> IEP4CommNeeded { get; set; }
        public Nullable<bool> IEP4AssistiveTechNeeded { get; set; }
        public Nullable<bool> IEP4EnglishProficiency { get; set; }
        public Nullable<bool> IEP4ImpedeLearning { get; set; }
        public string IEP5Disability { get; set; }
        public string IEP5OtherSpecify { get; set; }
        public string IEP5CIPCode { get; set; }
        public string IEP6TrainingGoal { get; set; }
        public string IEP6TrainCoursesStudy { get; set; }
        public string IEP6EmploymentGoal { get; set; }
        public string IEP6EmpCoursesStudy { get; set; }
        public string IEP6LivingGoal { get; set; }
        public string IEP6LivingCoursesStudy { get; set; }
        public Nullable<bool> IEP6MeasurableCheck1 { get; set; }
        public Nullable<bool> IEP6MeasurableCheck2 { get; set; }
        public Nullable<bool> IEP6MeasurableCheck3 { get; set; }
        public string IEP8PSSAReading { get; set; }
        public string IEP8PSSAappropriate { get; set; }
        public Nullable<bool> IEP8Videotape { get; set; }
        public Nullable<bool> IEP8WrittenNarrative { get; set; }
        public Nullable<bool> IEP8AsmtStdtGrade { get; set; }
        public Nullable<bool> IEP8AsmtWithoutAcc { get; set; }
        public Nullable<bool> IEP8LocalAltrntAssmnt { get; set; }
        public Nullable<bool> IEP8AsmtNotAdministred { get; set; }
        public Nullable<bool> IEP8ReadPartcptPSSAWithoutAcmdtn { get; set; }
        public Nullable<bool> IEP8ReadPartcptPSSAWithFollowingAcmdtn { get; set; }
        public Nullable<bool> IEP8ReadPartcptPSSAModiWithoutAcmdtn { get; set; }
        public Nullable<bool> IEP8ReadPartcptPSSAModiWithFollowingAcmdtn { get; set; }
        public Nullable<bool> IEP8SciencePartcptPSSAWithoutAcmdtn { get; set; }
        public Nullable<bool> IEP8SciencePartcptPSSAWithFollowingAcmdtn { get; set; }
        public Nullable<bool> IEP8SciencePartcptPSSAModiWithoutAcmdtn { get; set; }
        public Nullable<bool> IEP8SciencePartcptPSSAModiWithFollowingAcmdtn { get; set; }
        public Nullable<bool> IEP8MathPartcptPSSAWithoutAcmdtn { get; set; }
        public Nullable<bool> IEP8MathPartcptPSSAWithFollowingAcmdtn { get; set; }
        public Nullable<bool> IEP8MathPartcptPSSAModiWithoutAcmdtn { get; set; }
        public Nullable<bool> IEP8MathPartcptPSSAModiWithFollowingAcmdtn { get; set; }
        public Nullable<bool> IEP8WritePartcptPSSAWithoutAcmdtn { get; set; }
        public Nullable<bool> IEP8WritePartcptPSSAWithFollowingAcmdtn { get; set; }
        public string IEP8AltrntAssmntAppropriate { get; set; }
        public Nullable<bool> IEP8PSSAParticipate { get; set; }
        public Nullable<bool> IEP8AsmtWithAcc { get; set; }
        public string IEP8AssmtAcc { get; set; }
        public Nullable<bool> IEP9AlernativeAsmt { get; set; }
        public string IEP9NoRegAsmt { get; set; }
        public string IEP9AssmtAppropriate { get; set; }
        public string IEP10Benchmarks1 { get; set; }
        public string IEP10Benchmarks2 { get; set; }
        public string IEP10Benchmarks3 { get; set; }
        public Nullable<bool> IEP12ElegibleForESY { get; set; }
        public string IEP12ElegibleForESYInfo { get; set; }
        public Nullable<bool> IEP12NotElegibleForESY { get; set; }
        public string IEP12NotElegibleForESYInfo { get; set; }
        public string IEP12ShortTermObjectives { get; set; }
        public string IEP13RegularEdu { get; set; }
        public string IEP13GeneralEdu { get; set; }
        public Nullable<bool> IEP14Itinerant { get; set; }
        public Nullable<bool> IEP14Supplemental { get; set; }
        public Nullable<bool> IEP14FullTime { get; set; }
        public Nullable<bool> IEP14AutisticSupport { get; set; }
        public Nullable<bool> IEP14Blind { get; set; }
        public Nullable<bool> IEP14Deaf { get; set; }
        public Nullable<bool> IEP14Emotional { get; set; }
        public Nullable<bool> IEP14Learning { get; set; }
        public Nullable<bool> IEP14LifeSkills { get; set; }
        public Nullable<bool> IEP14MultipleDisabilities { get; set; }
        public Nullable<bool> IEP14Physical { get; set; }
        public Nullable<bool> IEP14Speech { get; set; }
        public string IEP14SchoolDistrict { get; set; }
        public string IEP14SchoolBuilding { get; set; }
        public Nullable<bool> IEP14IsNeighbour { get; set; }
        public Nullable<bool> IEP14IsNeibhourNo { get; set; }
        public Nullable<bool> IEP14SpclEdu { get; set; }
        public Nullable<bool> IEP14Other { get; set; }
        public Nullable<bool> IEP15RegularCls80 { get; set; }
        public Nullable<bool> IEP15Regular79 { get; set; }
        public Nullable<bool> IEP15Regular40 { get; set; }
        public Nullable<bool> IEP15ApprovePrivateSchool { get; set; }
        public string IEP15ApprovePrivateText { get; set; }
        public Nullable<bool> IEP15OtherPublic { get; set; }
        public string IEP15OtherPublicText { get; set; }
        public Nullable<bool> IEP15ApproveResidential { get; set; }
        public string IEP15ApproveResidentialText { get; set; }
        public Nullable<bool> IEP15Hospital { get; set; }
        public string IEP15HospitalText { get; set; }
        public Nullable<bool> IEP15PrivateFacility { get; set; }
        public string IEP15PrivateFacilityText { get; set; }
        public Nullable<bool> IEP15CorrectionalFacility { get; set; }
        public string IEP15CorrectionText { get; set; }
        public Nullable<bool> IEP15PrivateResi { get; set; }
        public string IEP15PrivateResText { get; set; }
        public Nullable<bool> IEP15ChkoutState { get; set; }
        public string IEP15ChkoutStateText { get; set; }
        public Nullable<bool> IEP15PublicFacility { get; set; }
        public string IEP15PublicFacilityText { get; set; }
        public Nullable<bool> IEP15InstructionConducted { get; set; }
        public string IEP15InstructionText { get; set; }
        public string IEP14OtherDesc { get; set; }
    }
}
