//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LE_LessonDetails
    {
        public int Le_DetailId { get; set; }
        public int LessonId { get; set; }
        public Nullable<int> SetValue { get; set; }
        public Nullable<int> StepValue { get; set; }
        public Nullable<int> NmbrObjects { get; set; }
        public string ObjectId { get; set; }
        public string Speed { get; set; }
        public string ClockBG { get; set; }
        public string IsDigits { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
