//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUp
    {
        public int LookupId { get; set; }
        public int SchoolId { get; set; }
        public string LookupType { get; set; }
        public string LookupName { get; set; }
        public string LookupCode { get; set; }
        public string LookupDesc { get; set; }
        public Nullable<int> ParentLookupId { get; set; }
        public string ParentLookupCode { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ActiveInd { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool isDynamic { get; set; }
    }
}
