//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int PlacementId { get; set; }
        public int StudentPersonalId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<int> PlacementType { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> BehaviorAnalyst { get; set; }
        public Nullable<int> PrimaryNurse { get; set; }
        public Nullable<int> UnitClerk { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> VisitationStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Reason { get; set; }
        public string AssociatedPersonnel { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<bool> IsMonday { get; set; }
        public string MondayNote { get; set; }
        public Nullable<bool> IsTuesday { get; set; }
        public string TuesdayNote { get; set; }
        public Nullable<bool> IsWednesday { get; set; }
        public string WednesdayNote { get; set; }
        public Nullable<bool> IsThursday { get; set; }
        public string ThursdayNote { get; set; }
        public Nullable<bool> IsFriday { get; set; }
        public string FridayNote { get; set; }
        public Nullable<bool> IsSaturday { get; set; }
        public string SaturdayNote { get; set; }
        public Nullable<bool> IsSunday { get; set; }
        public string SundayNote { get; set; }
        public Nullable<int> PlacementDepartment { get; set; }
        public Nullable<int> PlacementReason { get; set; }        
    }
}
