//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress_Report
    {
        public int Report_Id { get; set; }
        public Nullable<System.DateTime> Report_Date { get; set; }
        public string Report_Info { get; set; }
        public int GoalId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int StdtIEPId { get; set; }
        public Nullable<bool> AllowVisible { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
