//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrvsRecomendation
    {
        public int PrvsId { get; set; }
        public int StdtCvrId { get; set; }
        public string PreRecom { get; set; }
        public string PersonResp { get; set; }
        public string StatusUpdate { get; set; }
        public string PrvsRecordType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> CompletionDateGoal { get; set; }
        public Nullable<int> PersonResp2 { get; set; }
        public string RecNotes { get; set; }
        public string SubmissionStatus { get; set; }
    }
}
