//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_PlacementMeeting
    {
        public int PlacementId { get; set; }
        public int StudentPersonalId { get; set; }
        public int QueueStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> RatioNumerator { get; set; }
        public Nullable<int> RatioDenominator { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
