//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_ContractDetails
    {
        public int ContractDetId { get; set; }
        public int SchoolId { get; set; }
        public int StudentPersonalId { get; set; }
        public int QueueStatusId { get; set; }
        public Nullable<int> QueueId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string DistrictId { get; set; }
        public string CostShare { get; set; }
        public string Services { get; set; }
        public string ContactPersonName { get; set; }
        public string NoOfHours { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
		public Nullable<System.DateTime> EndDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }        
    }
}
