//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_CheckListAssign
    {
        public int AssignId { get; set; }
        public Nullable<int> QueueStatusId { get; set; }
        public int AcReviewId { get; set; }
        public int CheckListId { get; set; }
        public Nullable<int> CheckListHeaderId { get; set; }
        public string CheckListName { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool CompleteInd { get; set; }
        public string Type { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
