//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_LetterTrayValues
    {
        public int LetterTrayId { get; set; }
        public int QueueId { get; set; }
        public Nullable<int> StudentPersonalId { get; set; }
        public Nullable<int> LetterId { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TrayValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
