//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_Queue
    {
        public int QueueId { get; set; }
        public int SchoolId { get; set; }
        public string QueueName { get; set; }
        public string QueueType { get; set; }
        public int MasterId { get; set; }
        public int PrevQueueId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
