//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtIEPExt1
    {
        public int StdtIEPId { get; set; }
        public Nullable<bool> EngLangInd { get; set; }
        public Nullable<bool> HistInd { get; set; }
        public Nullable<bool> TechInd { get; set; }
        public Nullable<bool> MathInd { get; set; }
        public Nullable<bool> OtherInd { get; set; }
        public string OtherDesc { get; set; }
        public string AffectDesc { get; set; }
        public string AccomDesc { get; set; }
        public Nullable<bool> ContentModInd { get; set; }
        public string ContentModDesc { get; set; }
        public Nullable<bool> MethodModInd { get; set; }
        public string MethodModDesc { get; set; }
        public Nullable<bool> PerfModInd { get; set; }
        public string PerfModDesc { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
    }
}
