//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtDSStat
    {
        public int StdtDSStatId { get; set; }
        public int SchoolId { get; set; }
        public int StudentId { get; set; }
        public int DSTempHdrId { get; set; }
        public int LessonPlanId { get; set; }
        public string NextSetId { get; set; }
        public string NextStepId { get; set; }
        public Nullable<int> NextSetNmbr { get; set; }
        public string NextPromptId { get; set; }
        public string NextSessionNbr { get; set; }
        public string statusMessage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
    }
}
