//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtLPStg
    {
        public int StdtLPStgId { get; set; }
        public int SchoolId { get; set; }
        public int StudentId { get; set; }
        public string GoalName { get; set; }
        public Nullable<int> GoalCode { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public string AsmntName { get; set; }
        public string AsmntCat { get; set; }
        public string AsmntSubCat { get; set; }
        public string AsmntQId { get; set; }
        public string AsmntScr { get; set; }
        public string TotScr { get; set; }
        public Nullable<int> LessonPlanId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
