//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtScoreVw
    {
        public string StudentName { get; set; }
        public string StudentGender { get; set; }
        public Nullable<int> Age { get; set; }
        public string LessonPlanName { get; set; }
        public string SetName { get; set; }
        public string StepName { get; set; }
        public string PromptName { get; set; }
        public string CalcType { get; set; }
        public string ColName { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
        public string UserName { get; set; }
        public string TeacherGender { get; set; }
    }
}
