//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtSessStimuliActivity
    {
        public int StimulyActivityId { get; set; }
        public int DSTempHdrId { get; set; }
        public int SchoolId { get; set; }
        public int StudentId { get; set; }
        public int ClassId { get; set; }
        public string ActivitiType { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.DateTime> DateMastered { get; set; }
    }
}
