//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtAcdSheet
    {
        public int AccSheetId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> DateOfMeeting { get; set; }
        public string GoalArea { get; set; }
        public string Goal { get; set; }
        public string Benchmarks { get; set; }
        public string FeedBack { get; set; }
        public string PreposalDiss { get; set; }
        public string PersonResNdDeadline { get; set; }
        public string TypeOfInstruction { get; set; }
        public string Period1 { get; set; }
        public string Set1 { get; set; }
        public string Prompt1 { get; set; }
        public string IOA1 { get; set; }
        public string NoOfTimes1 { get; set; }
        public string Period2 { get; set; }
        public string Set2 { get; set; }
        public string Prompt2 { get; set; }
        public string IOA2 { get; set; }
        public string NoOfTimes2 { get; set; }
        public string Period3 { get; set; }
        public string Set3 { get; set; }
        public string Prompt3 { get; set; }
        public string IOA3 { get; set; }
        public string NoOfTimes3 { get; set; }
        public string Period4 { get; set; }
        public string Set4 { get; set; }
        public string Prompt4 { get; set; }
        public string IOA4 { get; set; }
        public string NoOfTimes4 { get; set; }
        public string Period5 { get; set; }
        public string Set5 { get; set; }
        public string Prompt5 { get; set; }
        public string IOA5 { get; set; }
        public string NoOfTimes5 { get; set; }
        public string Period6 { get; set; }
        public string Set6 { get; set; }
        public string Prompt6 { get; set; }
        public string IOA6 { get; set; }
        public string NoOfTimes6 { get; set; }
        public string Period7 { get; set; }
        public string Set7 { get; set; }
        public string Prompt7 { get; set; }
        public string IOA7 { get; set; }
        public string NoOfTimes7 { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> LessonPlanId { get; set; }
        public string Proposal { get; set; }
        public string Person { get; set; }
        public string Deadline { get; set; }
    }
}
