//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtLessonPlan
    {
        public int StdtLessonPlanId { get; set; }
        public int SchoolId { get; set; }
        public int StudentId { get; set; }
        public int LessonPlanId { get; set; }
        public Nullable<int> GoalId { get; set; }
        public int AsmntYearId { get; set; }
        public Nullable<int> StdtIEPId { get; set; }
        public Nullable<bool> IncludeIEP { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> MasteredDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> LessonPlanTypeDay { get; set; }
        public Nullable<int> LessonPlanTypeResi { get; set; }
        public string Objective { get; set; }
        public string Baseline { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Objective1 { get; set; }
        public string Objective2 { get; set; }
        public string Objective3 { get; set; }
        public Nullable<bool> isDynamic { get; set; }
    }
}
