//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtIEPExt2
    {
        public int StdtIEPId { get; set; }
        public Nullable<bool> PEInd { get; set; }
        public Nullable<bool> TechDevicesInd { get; set; }
        public Nullable<bool> BehaviorInd { get; set; }
        public Nullable<bool> BrailleInd { get; set; }
        public Nullable<bool> CommInd { get; set; }
        public Nullable<bool> CommDfInd { get; set; }
        public Nullable<bool> ExtCurInd { get; set; }
        public Nullable<bool> LEPInd { get; set; }
        public Nullable<bool> NonAcdInd { get; set; }
        public Nullable<bool> SocialInd { get; set; }
        public Nullable<bool> TravelInd { get; set; }
        public Nullable<bool> VocInd { get; set; }
        public Nullable<bool> OtherInd { get; set; }
        public string OtherDesc { get; set; }
        public Nullable<bool> AgeBand1Ind { get; set; }
        public Nullable<bool> AgeBand2Ind { get; set; }
        public Nullable<bool> AgeBand3Ind { get; set; }
        public string AffectDesc { get; set; }
        public string AccomDesc { get; set; }
        public Nullable<bool> ContentModInd { get; set; }
        public string ContentModDesc { get; set; }
        public Nullable<bool> MethodModInd { get; set; }
        public string MethodModDesc { get; set; }
        public Nullable<bool> PerfModInd { get; set; }
        public string PerfModDesc { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> C5DayInd { get; set; }
        public Nullable<bool> C6DayInd { get; set; }
        public Nullable<bool> C10DayInd { get; set; }
        public Nullable<bool> DayOther { get; set; }
        public string OtherDesc1 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
    }
}
