//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtAggScore
    {
        public int StdtAggScoreId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> DsTempSetColCalcId { get; set; }
        public Nullable<int> LessonPlanId { get; set; }
        public string CalcType { get; set; }
        public string ClassType { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<System.DateTime> AggredatedDate { get; set; }
        public Nullable<int> StdtSessEventId { get; set; }
        public string EventName { get; set; }
        public string IOAPerc { get; set; }
        public Nullable<int> MeasurementId { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> IOAUser { get; set; }
        public string IOAFrequency { get; set; }
        public string IOADuration { get; set; }
        public string ColRptLabelLP { get; set; }
    }
}
