//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtSessColScore
    {
        public int StdtSessColScore1 { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> DSTempSetColId { get; set; }
        public Nullable<int> DSTempSetColCalcId { get; set; }
        public Nullable<int> StdtSessionHdrId { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
