//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtSessionHdr
    {
        public int StdtSessionHdrId { get; set; }
        public int SchoolId { get; set; }
        public int StudentId { get; set; }
        public int DSTempHdrId { get; set; }
        public Nullable<int> StdtClassId { get; set; }
        public int LessonPlanId { get; set; }
        public Nullable<int> IOASessionHdrId { get; set; }
        public int SessionNbr { get; set; }
        public Nullable<System.DateTime> StartTs { get; set; }
        public Nullable<System.DateTime> EndTs { get; set; }
        public string SessMissTrailStus { get; set; }
        public int AssignedToId { get; set; }
        public Nullable<int> CurrentSetId { get; set; }
        public Nullable<int> CurrentStepId { get; set; }
        public Nullable<int> CurrentPromptId { get; set; }
        public string SessionStatusCd { get; set; }
        public string Comments { get; set; }
        public string IOAInd { get; set; }
        public Nullable<int> IOAUserId { get; set; }
        public Nullable<int> IOATotalTrial { get; set; }
        public Nullable<int> IOACorrectTrial { get; set; }
        public string IOAPerc { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsMaintanace { get; set; }
        public string IsTrial { get; set; }
    }
}
