//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtSessEvent
    {
        public int StdtSessEventId { get; set; }
        public int SchoolId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> LessonPlanId { get; set; }
        public Nullable<int> MeasurementId { get; set; }
        public Nullable<int> DSTempHdrId { get; set; }
        public string EventName { get; set; }
        public string StdtSessEventType { get; set; }
        public Nullable<int> SessionNbr { get; set; }
        public Nullable<int> SetId { get; set; }
        public Nullable<int> StepId { get; set; }
        public Nullable<int> PromptId { get; set; }
        public string Set_MoveUp { get; set; }
        public string Set_MoveDown { get; set; }
        public string Step_MoveUp { get; set; }
        public string Step_MoveDown { get; set; }
        public string Prompt_MoveUp { get; set; }
        public string Prompt_MoveDown { get; set; }
        public string IOAEvntStatus { get; set; }
        public string MultiTchrEvntStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> EvntTs { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> CheckStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> TimeStampForReport { get; set; }
        public Nullable<System.DateTime> CheckinTime { get; set; }
        public Nullable<System.DateTime> CheckoutTime { get; set; }
    }
}
