//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtIEP_PEUpdateStatus
    {
        public int stdtIEPPEUpdateStatusId { get; set; }
        public Nullable<int> stdtIEPId { get; set; }
        public Nullable<bool> Page1 { get; set; }
        public Nullable<bool> Page2 { get; set; }
        public Nullable<bool> Page3 { get; set; }
        public Nullable<bool> Page4 { get; set; }
        public Nullable<bool> Page5 { get; set; }
        public Nullable<bool> Page6 { get; set; }
        public Nullable<bool> Page7 { get; set; }
        public Nullable<bool> Page8 { get; set; }
        public Nullable<bool> Page9 { get; set; }
        public Nullable<bool> Page10 { get; set; }
        public Nullable<bool> Page11 { get; set; }
        public Nullable<bool> Page12 { get; set; }
        public Nullable<bool> Page13 { get; set; }
        public Nullable<bool> Page14 { get; set; }
        public Nullable<bool> Page15 { get; set; }
    }
}
