//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtCheckedIn
    {
        public int StdtCheckId { get; set; }
        public int StudentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.TimeSpan CheckIn { get; set; }
        public Nullable<System.TimeSpan> CheckOut { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
    }
}
