//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtIEPExt3
    {
        public int StdtIEPId { get; set; }
        public Nullable<bool> RemovedInd1 { get; set; }
        public Nullable<bool> RemovedInd2 { get; set; }
        public string RemovedDesc { get; set; }
        public string ShorterCd1 { get; set; }
        public string ShorterCd2 { get; set; }
        public string ShorterCd3 { get; set; }
        public string LongerCd3 { get; set; }
        public string LongerCd2 { get; set; }
        public string LongerCd1 { get; set; }
        public string SchedModDesc { get; set; }
        public Nullable<bool> TransportInd1 { get; set; }
        public Nullable<bool> TransportInd2 { get; set; }
        public Nullable<bool> RegTransInd { get; set; }
        public string RegTransDesc { get; set; }
        public Nullable<bool> SpTransInd { get; set; }
        public string SpTransDesc { get; set; }
        public string AsmntPlanned { get; set; }
        public Nullable<bool> EngCol1 { get; set; }
        public Nullable<bool> HistCol1 { get; set; }
        public Nullable<bool> MathCol1 { get; set; }
        public Nullable<bool> TechCol1 { get; set; }
        public Nullable<bool> ReadCol1 { get; set; }
        public Nullable<bool> EngCol2 { get; set; }
        public Nullable<bool> HistCol2 { get; set; }
        public Nullable<bool> MathCol2 { get; set; }
        public Nullable<bool> TechCol2 { get; set; }
        public Nullable<bool> ReadCol2 { get; set; }
        public Nullable<bool> EngCol3 { get; set; }
        public Nullable<bool> HistCol3 { get; set; }
        public Nullable<bool> MathCol3 { get; set; }
        public Nullable<bool> TechCol3 { get; set; }
        public Nullable<bool> ReadCol3 { get; set; }
        public string InfoCol2 { get; set; }
        public string InfoCol3 { get; set; }
        public Nullable<bool> AddInfoCol1 { get; set; }
        public Nullable<bool> AddInfoCol2 { get; set; }
        public Nullable<bool> AddInfoCol3 { get; set; }
        public string AddInfoCol3Desc { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedOn { get; set; }
    }
}
