//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdtAggScoreSet_Backup
    {
        public int StdtAggScore_SetId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SetId { get; set; }
        public Nullable<int> DSTempSetColCalcId { get; set; }
        public Nullable<System.DateTime> AggregatedDate { get; set; }
        public Nullable<int> LessonPlanId { get; set; }
        public string CalcType { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string ClassType { get; set; }
        public string IOAPerc { get; set; }
        public Nullable<bool> IsMaintanance { get; set; }
        public string ColRptLabelLP { get; set; }
    }
}
