//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> SASID { get; set; }
        public Nullable<int> JoinDt { get; set; }
        public Nullable<int> ResidenceInd { get; set; }
        public Nullable<int> Race { get; set; }
        public Nullable<int> LastPhysicalDate { get; set; }
        public Nullable<int> MedicalConditions { get; set; }
        public Nullable<int> Allergies { get; set; }
        public Nullable<int> CurrentMedications { get; set; }
        public Nullable<int> SelfPresAbility { get; set; }
        public Nullable<int> SignificantBehavior { get; set; }
        public Nullable<int> Capabilities { get; set; }
        public Nullable<int> Limitations { get; set; }
        public Nullable<int> Performances { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public Nullable<int> DistrictType { get; set; }
        public Nullable<int> DistFunction { get; set; }
        public Nullable<int> DistContactPerson { get; set; }
        public Nullable<int> Citizenship { get; set; }
        public Nullable<int> GuardenshipStatus { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string StudentLname { get; set; }
        public string StudentFname { get; set; }
        public string MiddleName { get; set; }
        public string StudentNbr { get; set; }
        public string Gender { get; set; }
        public string ImageUrl { get; set; }
        public string ActiveInd { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string PreferredName { get; set; }
        public string SortName { get; set; }
        public string NickName { get; set; }
        public string FullName { get; set; }
        public string Suffix { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int AddressId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public int StudentPersonalId { get; set; }
        public string GradeLevel { get; set; }
        public Nullable<int> ContactSequence { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public string LegalComp { get; set; }
        public string DistinguishMark { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string OtherStageAgency { get; set; }
        public string PrimaryLang { get; set; }
        public string CaseManagerEducational { get; set; }
        public string CaseManagerResidential { get; set; }
    }
}
