//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPersonalPA
    {
        public int StudentPersonalPAId { get; set; }
        public int StudentPersonalId { get; set; }
        public int SchoolId { get; set; }
        public string Bathroom { get; set; }
        public string OnCampus { get; set; }
        public string WhenTranspoting { get; set; }
        public string OffCampus { get; set; }
        public string CommonAreas { get; set; }
        public string PoolOrSwimming { get; set; }
        public string Van { get; set; }
        public string ho_CommonAres { get; set; }
        public string ho_BedroomAwake { get; set; }
        public string ho_BedroomAsleep { get; set; }
        public string dy_TaskOrBreak { get; set; }
        public string dy_TransitionInside { get; set; }
        public string dy_TransitionUnevenGround { get; set; }
        public string RiskOfResistance { get; set; }
        public string Mobility { get; set; }
        public string NeedForExtraHelp { get; set; }
        public string ResponseToInstruction { get; set; }
        public string Consciousness { get; set; }
        public string WalkingResponses { get; set; }
        public string Allergies { get; set; }
        public string Seizures { get; set; }
        public string Diet { get; set; }
        public string Other { get; set; }
        public string LiftingOrTransfers { get; set; }
        public string Ambulation { get; set; }
        public string Toileting { get; set; }
        public string Eating { get; set; }
        public string Showering { get; set; }
        public string Toothbrushing { get; set; }
        public string Dressing { get; set; }
        public string SkinCareOrSkinIntegrity { get; set; }
        public string Communication { get; set; }
        public string PreferedActivities { get; set; }
        public string GeneralInformation { get; set; }
        public string FundingSource { get; set; }
        public string SuggestedProactiveEnviornmentalProcedure { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
