//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentContactRelationship
    {
        public int StudentContactRelId { get; set; }
        public int ContactPersonalId { get; set; }
        public int RelationshipId { get; set; }
        public Nullable<bool> ParentLegalGuardian { get; set; }
        public Nullable<bool> PickupRights { get; set; }
        public Nullable<bool> LivesWith { get; set; }
        public Nullable<bool> AccessToRecords { get; set; }
        public Nullable<bool> EmergencyContact { get; set; }
        public Nullable<bool> HasCustody { get; set; }
        public Nullable<bool> DisciplinaryContact { get; set; }
        public Nullable<bool> PrimaryCareProvider { get; set; }
        public Nullable<bool> Other { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
