//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentOld
    {
        public int StudentId { get; set; }
        public int AddressId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string StudentNbr { get; set; }
        public string SASID { get; set; }
        public string StudentFname { get; set; }
        public string MiddleName { get; set; }
        public string StudentLname { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> JoinDt { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GradeLevel { get; set; }
        public string ActiveInd { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> ResidenceInd { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Race { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public string DistinguishMark { get; set; }
        public string CaseManagerResidential { get; set; }
        public string CaseManagerEducational { get; set; }
        public string LastPhysicalDate { get; set; }
        public string LegalComp { get; set; }
        public string MaritulStatus { get; set; }
        public string OtherStageAgency { get; set; }
        public string MedicalConditions { get; set; }
        public string Allergies { get; set; }
        public string CurrentMedications { get; set; }
        public string SelfPresAbility { get; set; }
        public string SignificantBehavior { get; set; }
        public string Capabilities { get; set; }
        public string Limitations { get; set; }
        public string Performances { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictType { get; set; }
        public string DistFunction { get; set; }
        public string DistContactPerson { get; set; }
        public string Citizenship { get; set; }
        public string GuardenshipStatus { get; set; }
        public string PrimaryLang { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
