//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPersonal
    {
        public int StudentPersonalId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string LocalId { get; set; }
        public string StateProvinceId { get; set; }
        public string Prefix { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string PreferredName { get; set; }
        public string SortName { get; set; }
        public string NickName { get; set; }
        public string PrimaryDiag { get; set; }
        public string SecondaryDiag { get; set; }
        public string SocialSecurityNo { get; set; }
        public string SSINo { get; set; }
        public string FullName { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> ImagePermission { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<bool> HispanicLatino { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> BirthDateVerification { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string PlaceOfBirth { get; set; }
        public string CountyOfBirth { get; set; }
        public Nullable<int> StateOfBirth { get; set; }
        public Nullable<int> CountryOfBirth { get; set; }
        public string CountryOfCitizenship { get; set; }
        public string CountryOfResidency { get; set; }
        public Nullable<System.DateTime> CountryArrivalDate { get; set; }
        public Nullable<int> CitizenshipStatus { get; set; }
        public Nullable<int> EnglishProficiency { get; set; }
        public string LanguageList { get; set; }
        public string DwellingArrangementCode { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<System.DateTime> ProjectedGraduationYear { get; set; }
        public Nullable<System.DateTime> OnTimeGraduationYear { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string PrimaryLanguage { get; set; }
        public string DistingushingMarks { get; set; }
        public string Ethinicity { get; set; }
        public string ReligiousAffiliation { get; set; }
        public string LegalCompetencyStatus { get; set; }
        public string OtherStateAgenciesInvolvedWithStudent { get; set; }
        public string MaritalStatusofBothParents { get; set; }
        public string GuardianShip { get; set; }
        public string CaseManagerEducational { get; set; }
        public string CaseManagerResidential { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public string MostRecentSchoolLocalId { get; set; }
        public string MostRecentHomeroomLocalId { get; set; }
        public Nullable<System.DateTime> DateInitiallyEligibleforSpecialEducation { get; set; }
        public Nullable<System.DateTime> DateofMostRecentSpecialEducationEvaluations { get; set; }
        public Nullable<System.DateTime> DateofNextScheduled3YearEvaluation { get; set; }
        public Nullable<System.DateTime> CurrentIEPStartDate { get; set; }
        public Nullable<System.DateTime> CurrentIEPExpirationDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public string LocationAfterDischarge { get; set; }
        public string MelmarkNewEnglandsFollowUpResponsibilities { get; set; }
        public string MostRecentGradeLevel { get; set; }
        public Nullable<bool> AcceptableUsePolicy { get; set; }
        public Nullable<bool> IDEA { get; set; }
        public Nullable<bool> Migrant { get; set; }
        public Nullable<bool> Title1 { get; set; }
        public Nullable<bool> GiftedTalented { get; set; }
        public Nullable<bool> EconomicDisadvantage { get; set; }
        public Nullable<bool> ELL { get; set; }
        public Nullable<bool> Homeless { get; set; }
        public Nullable<bool> Section504 { get; set; }
        public Nullable<bool> VocationalConcentrator { get; set; }
        public Nullable<bool> Immigrant { get; set; }
        public Nullable<bool> NeglectedDelinquent { get; set; }
        public Nullable<System.DateTime> FirstUSEnrollment { get; set; }
        public string StudentType { get; set; }
        public byte[] StudentXMLData { get; set; }
        public string IEPReferralFullName { get; set; }
        public string IEPReferralTitle { get; set; }
        public string IEPReferralPhone { get; set; }
        public string IEPReferralReferrinAgency { get; set; }
        public string IEPReferralSourceofTuition { get; set; }
        public Nullable<bool> FundingVerification { get; set; }
        public bool InactiveList { get; set; }
        public bool NewApplication { get; set; }
        public bool WaitingList { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Other { get; set; }
        public Nullable<bool> Ambulatory { get; set; }
        public string Intensive { get; set; }
        public string Notes { get; set; }
        public string SASID { get; set; }
        public string ReferralsSource { get; set; }
        public string Classification { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Medicaid { get; set; }
        public Nullable<bool> IsGuardian { get; set; }
        public string DayProgarm { get; set; }
        public string ClassroomWorkshop { get; set; }
        public string TeacherInstructor { get; set; }
        public string ProgramSpecialist { get; set; }
        public string EDUBehaviorAnalyst { get; set; }
        public string CurriculumCoordinator { get; set; }
        public string ResidentialProgram { get; set; }
        public string House { get; set; }
        public string ProgramManagerQMRP { get; set; }
        public string HouseSupervisor { get; set; }
        public string ResidentialBehaviorAnalyst { get; set; }
        public string PrimaryNurse { get; set; }
        public string UnitClerk { get; set; }
        public string PhotoPermComment { get; set; }
        public string PhotoRelease { get; set; }
        public string TripRestriction1 { get; set; }
        public string TripRestriction2 { get; set; }
        public string TripComments { get; set; }
        public string ClientInfoComments { get; set; }
        public Nullable<int> Classification1 { get; set; }
        public Nullable<int> Classification2 { get; set; }
        public Nullable<int> Classification3 { get; set; }
        public Nullable<int> Classification4 { get; set; }
        public Nullable<int> Classification5 { get; set; }
        public string PlacementStatus { get; set; }
        public Nullable<int> FundingSource { get; set; } //--- 22Sep2020 - List 3 - Task #2 ---//
    }
}
