//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public int AddressId { get; set; }
        public int SchoolId { get; set; }
        public string UserNo { get; set; }
        public string UserInitial { get; set; }
        public string UserFName { get; set; }
        public string UserLName { get; set; }
        public string Gender { get; set; }
        public byte[] Login { get; set; }
        public byte[] Password { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<System.DateTime> EffStartDate { get; set; }
        public Nullable<System.DateTime> EffEndDate { get; set; }
        public string ActiveInd { get; set; }
        public string ImageURL { get; set; }
        public string Position { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
