//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitation
    {
        public int VisitationId { get; set; }
        public int StudentPersonalId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<int> VisittaionType { get; set; }
        public string VisitationName { get; set; }
        public System.DateTime VisitationDate { get; set; }
        public System.DateTime ExpiredOn { get; set; }
        public Nullable<int> VisitationStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<int> Form { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Note { get; set; }
    }
}
